export const DashboardRoutes = (prefix) => [
  {
    path: '/',
    name: prefix + '.home',
    meta: { auth: true, name: 'header.home' },
    component: () => import('@/views/IndexPage1.vue'),
  },
  {
    path: '/dashboard1',
    name: prefix + '.dashboard1',
    meta: { auth: true, name: 'header.home1' },
    component: () => import('@/views/IndexPage.vue'),
  },
  {
    path: '/movie-list',
    name: prefix + '.movie-list',
    meta: { auth: true, name: 'sidebar.movie_list', title: 'Movie List' },
    component: () => import('../views/movie-list/MovieListPage.vue'),
  },
  {
    path: '/movie-genre',
    name: prefix + '.movie-genre',
    meta: { auth: true, name: 'header.movie-genre', isBanner: true, title: 'Movie Genre' },
    component: () => import('../views/movie-list/MovieGenre.vue'),
  },
  {
    path: '/movie-tags',
    name: prefix + '.movie-tags',
    meta: { auth: true, name: 'header.movie-tags', isBanner: true, title: 'Movie Tags' },
    component: () => import('../views/movie-list/MovieTags.vue'),
  },
  {
    path: '/movie-playlist',
    name: prefix + '.movie-playlist',
    meta: { auth: true, name: 'sidebar.movie-playlists', isBanner: true, title: 'Movie Playlist' },
    component: () => import('../views/movie-list/MoviePlalist.vue'),
  },
  {
    path: '/show-list',
    name: 'tv-shows.show-list',
    meta: { auth: true, name: 'sidebar.show_list', isBanner: true, title: 'Show Lists' },
    component: () => import('../views/tv-show/ShowListPage.vue'),
  },
  {
    path: '/episodes',
    name: 'show-list.episodes',
    meta: { auth: true, name: 'sidebar.episodes', isBanner: true, title: 'Episodes' },
    component: () => import('../views/tv-show/EpisodesPage.vue'),
  },
  {
    path: '/show-genre',
    name: 'show-list.show-genre',
    meta: { auth: true, name: 'sidebar.genre', isBanner: true, title: 'Genre' },
    component: () => import('../views/tv-show/ShowGenre.vue'),
  },
  {
    path: '/show-tag',
    name: 'show-list.show-tag',
    meta: { auth: true, name: 'sidebar.tags', isBanner: true, title: 'Tags' },
    component: () => import('../views/tv-show/ShowTags.vue'),
  },
  {
    path: '/show-playlist',
    name: 'show-list.show-playlist',
    meta: { auth: true, name: 'sidebar.playlist', isBanner: true, title: 'Playlist' },
    component: () => import('../views/tv-show/ShowPlaylist.vue'),
  },
  {
    path: '/videos',
    name: prefix + '.videos',
    meta: { auth: true, name: 'sidebar.videos', isBanner: true, title: 'Videos' },
    component: () => import('../views/videos/VideoPage.vue'),
  },
  {
    path: '/videos-category',
    name: prefix + '.videos-category',
    meta: { auth: true, name: 'sidebar.video-category', isBanner: true, title: 'Video Category' },
    component: () => import('../views/videos/VideoCategory.vue'),
  },
  {
    path: '/videos-tag',
    name: prefix + '.videos-tag',
    meta: { auth: true, name: 'sidebar.video-tags', isBanner: true, title: 'Video Tags' },
    component: () => import('../views/videos/VideoTag.vue'),
  },
  {
    path: '/videos-playlist',
    name: prefix + '.videos-playlist',
    meta: { auth: true, name: 'sidebar.video-playlist', isBanner: true, title: 'Video Playlist' },
    component: () => import('../views/videos/VideoPlaylist.vue'),
  },
  {
    path: '/person',
    name: prefix + '.person',
    meta: { auth: true, name: 'sidebar.person', isBanner: true, title: 'Person' },
    component: () => import('../views/persons/PersonPage.vue'),
  },
  {
    path: '/person-categories',
    name: prefix + '.person-categories',
    meta: { auth: true, name: 'dashboard.categories', isBanner: true, title: 'Categories' },
    component: () => import('../views/persons/PersonCategories.vue'),
  },
  {
    path: '/person-tag',
    name: prefix + '.person-tag',
    meta: { auth: true, name: 'fontawesome.tag', isBanner: true, title: 'Tag' },
    component: () => import('../views/persons/PersonTag.vue'),
  },
  {
    path: '/review',
    name: prefix + '.review',
    meta: { auth: true, name: 'sidebar.review', isBanner: true, title: 'Review' },
    component: () => import('../views/review/ReviewPage.vue'),
  },
  {
    path: '/comments',
    name: prefix + '.comments',
    meta: { auth: true, name: 'comments.Comment_List', isBanner: false, title: 'Comment List' },
    component: () => import('@/views/CommentPage.vue'),
  },
  {
    path: '/blank-page',
    name: prefix + '.blank-page',
    meta: { auth: true, name: 'sidebar.blank_page', isBanner: true, title: 'Blank Page' },
    component: () => import('@/views/BlankPage.vue'),
  },
  {
    path: '/alerts',
    name: 'ui-elements.alerts',
    meta: { auth: true, name: 'header.ui-alert', isBanner: true, title: 'Alerts' },
    component: () => import('@/views/ui-elements/AlertsView.vue'),
  },
  {
    path: '/avatars',
    name: 'ui-elements.avatars',
    meta: { auth: true, name: 'header.ui-avatars', isBanner: true, title: 'Avatars' },
    component: () => import('@/views/ui-elements/AvatarsView.vue'),
  },
  {
    path: '/badge',
    name: 'ui-elements.badge',
    meta: { auth: true, name: 'header.ui-badge', isBanner: true, title: 'Badge' },
    component: () => import('@/views/ui-elements/BadgeView.vue'),
  },
  {
    path: '/breadcrumb',
    name: 'ui-elements.breadcrumb',
    meta: { auth: true, name: 'header.ui-breadcrumb', isBanner: true, title: 'Breadcrumb' },
    component: () => import('@/views/ui-elements/BreadCrumb.vue'),
  },
  {
    path: '/buttons',
    name: 'ui-elements.buttons',
    meta: { auth: true, name: 'header.ui-button', isBanner: true, title: 'Buttons' },
    component: () => import('@/views/ui-elements/ButtonsView.vue'),
  },
  {
    path: '/buttonsgroup',
    name: 'ui-elements.buttonsgroup',
    meta: { auth: true, name: 'header.ui-button-group', isBanner: true, title: 'Buttons Group' },
    component: () => import('@/views/ui-elements/ButtonsGroup.vue'),
  },
  {
    path: '/offcanvas',
    name: 'ui-elements.offcanvas',
    meta: { auth: true, name: 'header.ui-offcanvas', isBanner: true, title: 'Off-Canvas' },
    component: () => import('@/views/ui-elements/OffCanvas.vue'),
  },
  {
    path: '/cards',
    name: 'ui-elements.cards',
    meta: { auth: true, name: 'header.ui-card', isBanner: true, title: 'Cards' },
    component: () => import('@/views/ui-elements/CardsView.vue'),
  },
  {
    path: '/carousel',
    name: 'ui-elements.carousel',
    meta: { auth: true, name: 'header.ui-carousel', isBanner: true, title: 'Carousel' },
    component: () => import('@/views/ui-elements/CarouselView.vue'),
  },
  {
    path: '/grid',
    name: 'ui-elements.grid',
    meta: { auth: true, name: 'header.ui-grid', isBanner: true, title: 'Grid' },
    component: () => import('@/views/ui-elements/GridView.vue'),
  },
  {
    path: '/images',
    name: 'ui-elements.images',
    meta: { auth: true, name: 'header.ui-images', isBanner: true, title: 'Images' },
    component: () => import('@/views/ui-elements/ImagesView.vue'),
  },
  {
    path: '/listgroup',
    name: 'ui-elements.listgroup',
    meta: { auth: true, name: 'header.ui-listgroup', isBanner: true, title: 'List Group' },
    component: () => import('@/views/ui-elements/ListGroup.vue'),
  },
  {
    path: '/modal',
    name: 'ui-elements.modal',
    meta: { auth: true, name: 'header.ui-modal', isBanner: true, title: 'Modal' },
    component: () => import('@/views/ui-elements/ModalView.vue'),
  },
  {
    path: '/notifications',
    name: 'ui-elements.notifications',
    meta: { auth: true, name: 'header.ui-notifications', isBanner: true, title: 'Notification' },
    component: () => import('@/views/ui-elements/NotificationsView.vue'),
  },
  {
    path: '/pagination',
    name: 'ui-elements.pagination',
    meta: { auth: true, name: 'header.ui-pagination', isBanner: true, title: 'Pagination' },
    component: () => import('@/views/ui-elements/PaginationView.vue'),
  },
  {
    path: '/popovers',
    name: 'ui-elements.popovers',
    meta: { auth: true, name: 'header.ui-popovers', isBanner: true, title: 'Popovers' },
    component: () => import('@/views/ui-elements/PopoversView.vue'),
  },
  {
    path: '/typography',
    name: 'ui-elements.typography',
    meta: { auth: true, name: 'header.ui-typography', isBanner: true, title: 'Typography' },
    component: () => import('@/views/ui-elements/TypographyView.vue'),
  },
  {
    path: '/tooltips',
    name: 'ui-elements.tooltips',
    meta: { auth: true, name: 'header.ui-tooltip', isBanner: true, title: 'Tooltips' },
    component: () => import('@/views/ui-elements/TooltipsView.vue'),
  },
  {
    path: '/tabs',
    name: 'ui-elements.tabs',
    meta: { auth: true, name: 'header.ui-tab', isBanner: true, title: 'Tabs' },
    component: () => import('@/views/ui-elements/TabsView.vue'),
  },
  {
    path: '/video',
    name: 'ui-elements.video',
    meta: { auth: true, name: 'header.ui-embedvideo', isBanner: true, title: 'Video' },
    component: () => import('@/views/ui-elements/VideoView.vue'),
  },

  // Spacial Pages
  {
    path: '/category-list',
    name: 'special-pages.billing',
    meta: { auth: true, name: 'header.category_list', isBanner: true, title: 'Category List' },
    component: () => import('../views/CatregoryListPage.vue'),
  },

  {
    path: '/pricing',
    name: 'special-pages.pricing',
    meta: { auth: true, name: 'sidebar.pricing', isBanner: true, title: 'Pricing' },
    component: () => import('@/views/spacial-pages/PricingPage.vue'),
  },

  {
    path: '/user-list',
    name: 'user.user-list',
    meta: { auth: true, name: 'header.user-list', isBanner: true, title: 'User List' },
    component: () => import('@/views/user/ListPage.vue'),
  },
  {
    path: '/user-add',
    name: 'user.user-add',
    meta: { auth: true, name: 'header.user-add', isBanner: true, title: 'User Add' },
    component: () => import('@/views/user/AddPage.vue'),
  },
  {
    path: '/user-profile',
    name: 'user.user-profile',
    meta: { auth: true, name: 'header.user-profile', isBanner: true, title: 'User Profile' },
    component: () => import('@/views/user/ProfilePage.vue'),
  },
  {
    path: '/privacy-setting',
    name: 'user.user-privacy-setting',
    meta: { auth: true, name: 'header.privacy_setting', isBanner: true, title: 'Privacy Setting' },
    component: () => import('@/views/user/PrivacySetting.vue'),
  },

  // Widgets Pages
  {
    path: '/widget-basic',
    name: 'widget.widget-basic',
    meta: { auth: true, name: 'header.basic_widget', isBanner: true, title: 'Widget Basic' },
    component: () => import('@/views/widgets/WidgetBasic.vue'),
  },
  {
    path: '/widget-chart',
    name: 'widget.widget-chart',
    meta: { auth: true, name: 'header.widget_chart', isBanner: true, title: 'Widget Chart' },
    component: () => import('@/views/widgets/WidgetChart.vue'),
  },
  {
    path: '/widget-card',
    name: 'widget.widget-card',
    meta: { auth: true, name: 'header.widget_card', isBanner: true, title: 'Widget Card' },
    component: () => import('@/views/widgets/WidgetCard.vue'),
  },
  // Form Pages
  {
    path: '/elements',
    name: 'form.elements',
    meta: { auth: true, name: 'header.form-elements', isBanner: true, title: 'Form Elements' },
    component: () => import('@/views/forms/ElementsPage.vue'),
  },
  {
    path: '/validation',
    name: 'form.validation',
    meta: { auth: true, name: 'header.form-validation', isBanner: true, title: 'Form Validation' },
    component: () => import('@/views/forms/ValidationPage.vue'),
  },
  {
    path: '/wizard',
    name: 'form.wizard',
    meta: { auth: true, name: 'header.form-wizard', isBanner: true, title: 'Form Wizard' },
    component: () => import('@/views/forms/WizardPage.vue'),
  },
  // Table Pages
  {
    path: '/bootstrap-table',
    name: 'table.bootstrap-table',
    meta: { auth: true, name: 'header.bootstrap_table', isBanner: true, title: 'Bootstrap Table' },
    component: () => import('@/views/tables/BootstrapTable.vue'),
  },
  {
    path: '/border-table',
    name: 'table.border-table',
    meta: { auth: true, name: 'header.border_table', isBanner: true, title: 'Border Table' },
    component: () => import('@/views/tables/BorderTable.vue'),
  },
  {
    path: '/data-table',
    name: 'table.data-table',
    meta: { auth: true, name: 'header.table-data', isBanner: true, title: 'Data Table' },
    component: () => import('@/views/tables/DataTable.vue'),
  },
  {
    path: '/fancy-table',
    name: 'table.fancy-table',
    meta: { auth: true, name: 'header.fancy_table', isBanner: true, title: 'Fancy Table' },
    component: () => import('@/views/tables/FancyTable.vue'),
  },
  {
    path: '/fixed-table',
    name: 'table.fixed-table',
    meta: { auth: true, name: 'header.fixed_table', isBanner: true, title: 'Fixed Table' },
    component: () => import('@/views/tables/FixedTable.vue'),
  },
  // Icons Pages
  {
    path: '/ph-regular',
    name: 'icons.ph-regular',
    meta: { auth: true, name: 'sidebar.ph-regular', isBanner: true, title: 'Ph Regular' },
    component: () => import('../views/icons/PhRegular.vue'),
  },
  {
    path: '/ph-bold',
    name: 'icons.ph-bold',
    meta: { auth: true, name: 'sidebar.ph-bold', isBanner: true, title: 'Ph Bold' },
    component: () => import('../views/icons/PhBold.vue'),
  },
  {
    path: '/ph-fill',
    name: 'icons.ph-fill',
    meta: { auth: true, name: 'sidebar.ph-fill', isBanner: true, title: 'Ph Fill' },
    component: () => import('../views/icons/PhFill.vue'),
  },
  {
    path: '/access-control',
    name: 'icons.access-control',
    meta: { auth: true, name: 'sidebar.access_control', isBanner: true, title: 'Access Control Icons' },
    component: () => import('../views/icons/AccessControl.vue'),
  },
  {
    path: '/ui-color',
    name: prefix + '.ui-color',
    meta: { auth: true, name: 'header.ui-color', isBanner: true, title: 'Colors' },
    component: () => import('@/views/extra/UiColorPage.vue'),
  },
  {
    path: '/privacy-policy',
    name: prefix + '.privacy-policy',
    meta: { auth: true, name: 'header.privacy-policy', isBanner: true, title: 'Privacy Policy' },
    component: () => import('@/views/extra/PrivacyPolicy.vue'),
  },
  {
    path: '/terms-and-conditions',
    name: prefix + '.terms-and-conditions',
    meta: { auth: true, name: 'header.terms_of_use', isBanner: true, title: 'Terms of Use' },
    component: () => import('@/views/extra/TermsAndConditions.vue'),
  },
  {
    path: '/rating',
    name: prefix + '.rating',
    meta: { auth: true, name: 'sidebar.rating' },
    component: () => import('../components/rating/RatingPage.vue'),
  },
];

export const AuthChildRoutes = (prefix) => [
  {
    path: '/auth/login',
    name: prefix + '.login',
    meta: { auth: false, name: 'sidebar.login' },
    component: () => import('../views/auth/default/SignIn.vue'),
  },
  {
    path: '/auth/register',
    name: prefix + '.register',
    meta: { auth: false, name: 'sidebar.register' },
    component: () => import('../views/auth/default/SignUp.vue'),
  },
  {
    path: '/auth/reset-password',
    name: prefix + '.reset-password',
    meta: { auth: false, name: 'authentication.reset_password' },
    component: () => import('../views/auth/default/ResetPassword.vue'),
  },
  {
    path: '/auth/verify-email',
    name: prefix + '.varify-email',
    meta: { auth: false, name: 'header.varify-email' },
    component: () => import('../views/auth/default/VarifyEmail.vue'),
  },
  {
    path: '/auth/two-factor',
    name: prefix + '.two-factor',
    meta: { auth: false, name: 'header.twofactor' },
    component: () => import('../views/auth/default/TwoFactor.vue'),
  },
  {
    path: '/auth/account-deactivated',
    name: prefix + '.account-deactivated',
    meta: { auth: false, name: 'header.accountdeactivated' },
    component: () => import('../views/auth/default/AccountDeactivated.vue'),
  },
  {
    path: '/auth/lock-screen',
    name: prefix + '.lock-screen',
    meta: { auth: false, name: 'sidebar.lock_screen' },
    component: () => import('../views/auth/default/LockScreen.vue'),
  },
];
//error routes
export const AuthErrorRoutes = () => [
  {
    path: '/error-500',
    name: 'error.500',
    meta: { auth: true, name: '.500' },
    component: () => import('../views/errors/Error500Page.vue'),
  },
  {
    path: '/error-404',
    name: 'error.404',
    meta: { auth: true, name: '.error' },
    component: () => import('../views/errors/Error404Page.vue'),
  },
  {
    path: '/maintenance',
    name: 'error.maintenance',
    meta: { auth: true, name: '.maintenance' },
    component: () => import('../views/errors/MaintenancePage.vue'),
  },
  {
    path: '/coming-soon',
    name: 'error.coming-soon',
    meta: { auth: true, name: '.coming-soon' },
    component: () => import('../views/errors/coming-soon.vue'),
  },
];
