import { blogsDetails } from './blog-details';
import { generateImgPath } from './data';
export const filterBlog = (slug) => blogsGrid.find((item) => item.slug === slug);
export const filterBlogDetail = (slug) => blogsDetails.find((item) => item.slug === slug).detail;
export const dateWiseBlogs = (date) => blogs.filter((item) => item.blogDate.includes(date));
export const categoryWiseBlogs = (category) => blogs.filter((item) => item.categories.includes(category));
export const tagsWiseBlogs = (tag) => blogs.filter((item) => item.tags.includes(tag));

export const blogTags = [
  {
    id: 1,
    slug: "drama",
    name: "streamTag.drama",
  },
  {
    id: 2,
    slug: "action",
    name: "streamTag.action",
  },
  {
    id: 3,
    slug: "comedies",
    name: "streamTag.comedy",
  },
  {
    id: 4,
    slug: "drama",
    name: "streamTag.drama",
  },
  {
    id: 5,
    slug: "dramas",
    name: "streamTag.drama",
  },
  {
    id: 6,
    slug: "historical",
    name: "streamTag.history",
  },
  {
    id: 7,
    slug: "horr",
    name: "streamTag.horror",
  },
  {
    id: 8,
    slug: "horror",
    name: "streamTag.horror",
  },
  {
    id: 9,
    slug: "movie",
    name: "streamBlogTag.movy",
  },
  {
    id: 10,
    slug: "movie-trailers",
    name: "streamBlogCategory.movie_trailers",
  },
  {
    id: 11,
    slug: "mystery",
    name: "streamTag.mystery",
  },
  {
    id: 12,
    slug: "rumors",
    name: "streamBlogTag.tv_rumors",
  },
  {
    id: 13,
    slug: "thrill",
    name: "streamTag.thriller",
  },
  {
    id: 14,
    slug: "thriller",
    name: "streamTag.thriller",
  },
  {
    id: 15,
    slug: "trailer",
    name: "streamBlogTag.trailer",
  },
  {
    id: 16,
    slug: "tv rumors",
    name: "streamBlogTag.tv_rumors",
  },
  {
    id: 17,
    slug: "tv series",
    name: "streamBlogTag.tv_series",
  },
];
export const blogCategories = [
  {
    id: 1,
    title: "streamTag.drama",
    post_count: "4",
  },
  {
    id: 2,
    title: "streamBlogTag.history",
    post_count: "7",
  },
  {
    id: 3,
    title: "streamBlogTag.movy",
    post_count: "2",
  },
  {
    id: 4,
    title: "streamBlogCategory.movie_trailers",
    post_count: "6",
  },
  {
    id: 5,
    title: "streamBlogTag.trailer",
    post_count: "4",
  },
  {
    id: 6,
    title: "streamBlogTag.tv_comedies",
    post_count: "3",
  },
  {
    id: 7,
    title: "streamBlogTag.tv_rumors",
    post_count: "4",
  },
  {
    id: 8,
    title: "streamBlogTag.tv_series",
    post_count: "5",
  },
];

export const blogs = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/blog/rebirth-of-the-realm.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog1",
    description:"streamBlog.blog1_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/blog/Special-Effects.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog2",
    description:"streamBlog.blog2_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/blog/to-be-continue.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog3",
    description:"streamBlog.blog3_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 4,
    thumbnail: generateImgPath("/assets/images/blog/duos-standing.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog4",
    description:"streamBlog.blog4_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 5,
    thumbnail: generateImgPath("/assets/images/blog/short-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog5",
    description:"streamBlog.blog5_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 6,
    thumbnail: generateImgPath("/assets/images/blog/beloved.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog6",
    description:"streamBlog.blog6_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 7,
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog7",
    description:"streamBlog.blog7_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 8,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog8",
    description:"streamBlog.blog8_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 9,
    thumbnail: generateImgPath("/assets/images/blog/Independent.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog9",
    description:"streamBlog.blog9_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 10,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog10",
    description:"streamBlog.blog10_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 11,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog11",
    description:"streamBlog.blog11_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 12,
    thumbnail: generateImgPath("/assets/images/blog/comedy-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog12",
    description:"streamBlog.blog12_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 13,
    thumbnail: generateImgPath("/assets/images/blog/kisds-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog13",
    description:"streamBlog.blog13_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 14,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog14",
    description:"streamBlog.blog14_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: ["streamBlogCategory.drama"],
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
];

export const blogsGrid = [
  {
    id: 1,
    thumbnail: generateImgPath("/assets/images/blog/rebirth-of-the-realm.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog1",
    description:"streamBlog.blog1_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 2,
    thumbnail: generateImgPath("/assets/images/blog/Special-Effects.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog2",
    description:"streamBlog.blog2_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 3,
    thumbnail: generateImgPath("/assets/images/blog/to-be-continue.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog3",
    description:"streamBlog.blog3_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 4,
    thumbnail: generateImgPath("/assets/images/blog/duos-standing.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog4",
    description:"streamBlog.blog4_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 5,
    thumbnail: generateImgPath("/assets/images/blog/short-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog5",
    description:"streamBlog.blog5_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 6,
    thumbnail: generateImgPath("/assets/images/blog/beloved.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog6",
    description:"streamBlog.blog6_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 7,
    thumbnail: generateImgPath("/assets/images/blog/blog9.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog7",
    description:"streamBlog.blog7_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 8,
    thumbnail: generateImgPath("/assets/images/blog/blog8.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog8",
    description:"streamBlog.blog8_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 9,
    thumbnail: generateImgPath("/assets/images/blog/Independent.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog9",
    description:"streamBlog.blog9_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
  {
    id: 10,
    thumbnail: generateImgPath("/assets/images/blog/blog5.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog10",
    description:"streamBlog.blog10_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 11,
    thumbnail: generateImgPath("/assets/images/blog/blog4.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog11",
    description:"streamBlog.blog11_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 12,
    thumbnail: generateImgPath("/assets/images/blog/comedy-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog12",
    description:"streamBlog.blog12_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 13,
    thumbnail: generateImgPath("/assets/images/blog/kisds-movie.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog13",
    description:"streamBlog.blog13_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },

  {
    id: 14,
    thumbnail: generateImgPath("/assets/images/blog/blog1.webp"),
    blogDate: "January 10, 2025",
    userImage: generateImgPath("/assets/images/user/user3.webp"),
    username: "streamAccount.jenny",
    slug: "the-most-anticipated-movies",
    title: "streamBlog.blog14",
    description:"streamBlog.blog14_desc",
    longDescription: filterBlogDetail("simple-blog"),
    categories: "streamBlogCategory.drama",
    tags: ["streamBlogTag.comedies", "streamTag.drama", "streamBlogCategory.movie_trailers"],
    category:["streamBlogCategory.history","streamBlogCategory.movy", "streamBlogCategory.trailer" ,"streamBlogCategory.tv_series"],
  },
];

export const blogSidebar = [
  {
    id: '01',
    blogImg: 'blog1.webp',
    slug: 'the-most-anticipated-movies',
    blogDate: 'January 10, 2025',
    blogTag: 'Jenny',
    blogTitle: 'blogs.anticipated_movies',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
  {
    id: '02',
    blogImg: 'blog4.webp',
    slug: 'everything-you-need-to-know-about',
    blogDate: 'January 10, 2025',
    blogTag: 'Jenny',
    blogTitle: 'blogs.everything_about',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
  {
    id: '03',
    blogImg: 'blog5.webp',
    slug: 'my-streaming-black-pearl',
    blogDate: 'January 10, 2025',
    blogTag: 'Jenny',
    blogTitle: 'blogs.black_pearl',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
  {
    id: '04',
    blogImg: 'blog7.webp',
    slug: 'cookies-and-web-beacons',
    blogDate: 'February1, 2019',
    blogTag: 'Jenny',
    blogTitle: 'blogs.cookies_web',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
  {
    id: '05',
    blogImg: 'blog8.webp',
    slug: 'birds-of-prey-star-says-shes-definitely-open-to-a-ghost-return',
    blogDate: 'January 30, 2019',
    blogTag: 'Jenny',
    blogTitle: 'blogs.birds_of_prey',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
  {
    id: '06',
    blogImg: 'blog9.webp',
    slug: 'saturday-night-live-re-enacts-biden-and-harris-victory-speeches',
    blogDate: 'January 30, 2019',
    blogTag: 'Jenny',
    blogTitle: 'blogs.saturday_night',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
  {
    id: '07',
    blogImg: 'blog10.webp',
    slug: 'gillian-anderson-shares-the-photos-from-the-crown',
    blogDate: 'January 30, 2019',
    blogTag: 'Jenny',
    blogTitle: 'streamForm.gillian_shares',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true
  },
];
export const blogGrid2 = [
  {
    id: '01',
    blogImg: 'blog1.webp',
    slug: 'emmy-2018-game-of-throne-featured-having-22-nominee',
    blogDate: 'January 1, 2022',
    blogTag: 'Movie',
    blogTitle: 'blogs.emmy_2018',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '02',
    blogImg: 'blog2.webp',
    slug: '10-teams-we-cant-wait-to-use-in-soccer-2022',
    blogDate: 'February 2, 2022',
    blogTag: 'Trailers',
    blogTitle: 'blogs.soccer_2022',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '03',
    blogImg: 'blog3.webp',
    slug: '10-free-games-with-gold-of-july-2022-are-out',
    blogDate: 'January 30, 2022',
    blogTag: 'Movie',
    blogTitle: 'blogs.free_gold',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '04',
    blogImg: 'blog4.webp',
    slug: 'island-2-is-still-in-deving-magic-confirms',
    blogDate: 'January 30, 2022',
    blogTag: 'Trailers',
    blogTitle: 'blogs.island_2',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '05',
    blogImg: 'blog5.webp',
    slug: 'drum-gum-added-in-4-5-update',
    blogDate: 'January 30, 2022',
    blogTag: 'Trailers',
    blogTitle: 'blogs.drum_gum',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '06',
    blogImg: 'blog6.webp',
    slug: 'racing-is-about-to-show-you-the-beauty-of-britain',
    blogDate: 'February 2, 2022',
    blogTag: 'TV Series',
    blogTitle: 'blogs.racing_show',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '07',
    blogImg: 'blog7.webp',
    slug: 'merghani-alonso-wins-esport-league',
    blogDate: 'February 1, 2022',
    blogTag: 'Historical',
    blogTitle: 'blogs.merghani_league',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '08',
    blogImg: 'blog8.webp',
    slug: 'a-free-pc-game-is-still-available-through-ae',
    blogDate: 'February 2, 2022',
    blogTag: 'Trailers',
    blogTitle: 'A Free PC Game is still available Through AE',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '09',
    blogImg: 'blog9.webp',
    slug: 'how-turned-hot-wheels-into-sheer-genius',
    blogDate: 'February 1, 2022',
    blogTag: 'Historical',
    blogTitle: 'blogs.hot_wheels',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  },
  {
    id: '10',
    blogImg: 'blog10.webp',
    slug: 'grab-free-skin-and-loot-from-phone',
    blogDate: 'January 30, 2022',
    blogTag: 'Movie',
    blogTitle: 'blogs.grab_free_skin',
    blogText: 'blogs.blog_desc',
    linkButton: true,
    rightIcon: true,
    categoriesList: [],
  }
];

export const blogRecent = [filterBlog('the-most-anticipated-movies'), filterBlog('amy-adams-always-dreamed'), filterBlog('wandaVision-will-reveal-scarlet-witch’s-untapped-powers')].filter((item) => item !== undefined);
export const blogRecents = [filterBlog('the-most-anticipated-movies'), filterBlog('amy-adams-always-dreamed'), filterBlog('wandaVision-will-reveal-scarlet-witch’s-untapped-powers'), filterBlog('everything-you-need-to-know-about'), filterBlog('my-streaming-black-pearl')].filter((item) => item !== undefined);

// export const blogPagination = [filterBlog()]
